### ISSUE TITLE
WordPress 5.5 Updates

### ISSUE THREAD

**Issue by vinkla** [wordplate/mail#14]
[WordPress 5.5 will ship with a new version of PHPMailer.](https://make.wordpress.org/core/2020/07/01/external-library-updates-in-wordpress-5-5-call-for-testing/) Do we need to update this package in order to support the changes?

ping @fiskhandlarn @puredazzle

**Comment by fiskhandlarn** [comment]
Probably. At least change the namespace for https://github.com/wordplate/mail/blob/master/src/Mail.php#L16 right? I'm not sure if the methods used on the phpmailer instance has changed from v 5.2 to 6.0?

**Comment by vinkla** [comment]
That is true. Are you currently using this package? Would you mind taking charge of the update?

**Comment by b4nghh** [comment]
I already opened an PR. Please take a look!

**Comment by vinkla** [comment]
Fixed in #15
