### ISSUE TITLE
Incompatible with new framework version

### ISSUE THREAD

**Issue by sandrodz** [wordplate/mail#6]
<img width="1049" alt="screen shot 2017-10-16 at 9 29 23 pm" src="https://user-images.githubusercontent.com/8479569/31626013-350aa6ec-b2b9-11e7-974e-418b13b57dab.png">

**Comment by sandrodz** [comment]
that was fast! thanks @vinkla

**Comment by vinkla** [comment]
Thanks for reporting! I've released a new version.
